"""Typed vocabulary for the VisionCore AI assistant.

Phase 7 adds a conversational assistant on top of the deterministic vision
pipeline. Two rules shape everything in this package:

* The assistant is only a *producer of intents*. It never touches the mouse,
  the device layer, the operating system, a shell or a network file. It answers
  questions and, at most, proposes one action from a fixed allowlist; the
  existing control layers and their safety gate decide whether that action may
  run at all.
* Nothing here pretends. A reply is tagged with the source it really came from
  (:class:`ResponseSource`), the status shown to the user is the status the
  assistant is genuinely in (:class:`AIStatus`), and a request that was never
  sent is never described as thinking.

Conversations are held in memory only: they are discarded when VisionCore exits
and are never written to disk.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Tuple


class ChatRole(str, Enum):
    """Who produced a conversation entry."""

    USER = "USER"
    ASSISTANT = "ASSISTANT"
    SYSTEM = "SYSTEM"

    @property
    def label(self) -> str:
        return {"USER": "You", "ASSISTANT": "VisionCore", "SYSTEM": "System"}[self.value]


class ResponseSource(str, Enum):
    """Where a reply actually came from.

    Kept explicit so a provider-generated answer can never be confused with a
    deterministic local answer, either in the interface or in the logs.
    """

    PROVIDER = "PROVIDER"      # generated by the configured AI provider
    LOCAL = "LOCAL"            # deterministic local answer, no model involved
    SYSTEM = "SYSTEM"          # produced by VisionCore itself (results, errors)

    @property
    def label(self) -> str:
        if self is ResponseSource.PROVIDER:
            return "AI"
        if self is ResponseSource.LOCAL:
            return "LOCAL"
        return "SYSTEM"


class AIStatus(str, Enum):
    """Assistant status shown to the user (Phase 7, section 17).

    ``THINKING`` is only ever entered while a request is genuinely in flight
    with the provider, so the interface never fakes processing.
    """

    NOT_CONFIGURED = "NOT_CONFIGURED"
    READY = "READY"
    THINKING = "THINKING"
    RESPONDING = "RESPONDING"
    EXECUTING = "EXECUTING"
    ERROR = "ERROR"

    @property
    def label(self) -> str:
        # A request that really is with the provider is described as processing.
        if self is AIStatus.THINKING:
            return "PROCESSING"
        if self is AIStatus.NOT_CONFIGURED:
            return "NOT CONFIGURED"
        return self.value

    @property
    def busy(self) -> bool:
        return self in (AIStatus.THINKING, AIStatus.RESPONDING, AIStatus.EXECUTING)


class AIActionKind(str, Enum):
    """The only action families the assistant may request."""

    DEVICE_ACTION = "DEVICE_ACTION"    # volume, media, brightness, window
    CONTROL_MODE = "CONTROL_MODE"      # MOUSE <-> DEVICE
    CONTROL_ACTION = "CONTROL_ACTION"  # pause / resume / disarm mouse control


class AIErrorKind(str, Enum):
    """Why an AI request could not be answered."""

    NOT_CONFIGURED = "NOT_CONFIGURED"
    TIMEOUT = "TIMEOUT"
    RATE_LIMIT = "RATE_LIMIT"
    AUTH = "AUTH"
    UNAVAILABLE = "UNAVAILABLE"
    MALFORMED = "MALFORMED"
    REJECTED = "REJECTED"        # valid transport, but the answer was refused
    INTERNAL = "INTERNAL"

    @property
    def label(self) -> str:
        return {
            AIErrorKind.NOT_CONFIGURED: "AI NOT CONFIGURED",
            AIErrorKind.TIMEOUT: "AI PROVIDER TIMEOUT",
            AIErrorKind.RATE_LIMIT: "AI PROVIDER RATE LIMIT",
            AIErrorKind.AUTH: "AI PROVIDER AUTH FAILED",
            AIErrorKind.UNAVAILABLE: "AI PROVIDER UNAVAILABLE",
            AIErrorKind.MALFORMED: "AI RESPONSE UNREADABLE",
            AIErrorKind.REJECTED: "ACTION REFUSED",
            AIErrorKind.INTERNAL: "AI INTERNAL ERROR",
        }[self]


@dataclass(frozen=True, slots=True)
class ChatMessage:
    """One conversation entry (memory only, never persisted)."""

    role: ChatRole
    content: str
    timestamp: float = 0.0
    source: ResponseSource = ResponseSource.SYSTEM
    detail: str = ""

    @property
    def label(self) -> str:
        return self.role.label


@dataclass(frozen=True, slots=True)
class AIActionPlan:
    """A validated, allowlisted action the assistant proposes.

    ``action`` is always one of the fixed allowlist keys; it is never a free
    form command and it is never executed by this layer. The intent that carries
    it to a controller is built by :mod:`app.ai.router`.
    """

    kind: AIActionKind
    action: str
    label: str
    requires_confirmation: bool = False

    @property
    def signature(self) -> str:
        return f"{self.kind.value}:{self.action}"


@dataclass(frozen=True, slots=True)
class AIReply:
    """A produced reply: text plus an optional (still unvalidated) action."""

    text: str
    action: Optional[AIActionPlan] = None
    source: ResponseSource = ResponseSource.PROVIDER


@dataclass(frozen=True, slots=True)
class AIActionOutcome:
    """The real result of executing a plan, as reported by the owning layer."""

    plan: AIActionPlan
    accepted: bool = False        # the intent router accepted the intent
    executed: bool = False        # the owning controller performed it
    success: bool = False         # the backend really did it
    message: str = ""             # real controller message, verbatim
    reason: str = ""              # refusal reason when it did not run

    @property
    def detail(self) -> str:
        return self.message or self.reason


@dataclass(frozen=True, slots=True)
class AISnapshot:
    """Immutable view of the assistant for one frame."""

    status: AIStatus = AIStatus.NOT_CONFIGURED
    provider: str = "NONE"
    model: str = ""
    configured: bool = False
    messages: Tuple[ChatMessage, ...] = ()
    pending: Optional[AIActionPlan] = None
    pending_seconds: float = 0.0
    error: Optional[AIErrorKind] = None
    error_detail: str = ""
    note: str = ""
    in_flight: bool = False
    turns: int = 0

    @property
    def status_label(self) -> str:
        return self.status.label

    @property
    def busy(self) -> bool:
        return self.status.busy

    @property
    def header_note(self) -> str:
        """Compact provider note for the header button."""
        if not self.configured:
            return "NOT CONFIGURED"
        return self.model or self.provider


@dataclass(frozen=True, slots=True)
class AIRequest:
    """One request handed to the background client."""

    request_id: int
    messages: Tuple[ChatMessage, ...]
    context: str = ""
    timestamp: float = 0.0


@dataclass(frozen=True, slots=True)
class AIResult:
    """The outcome of one background request."""

    request_id: int
    reply: Optional[AIReply] = None
    error: Optional[AIErrorKind] = None
    detail: str = ""
    cancelled: bool = False

    @property
    def ok(self) -> bool:
        return self.reply is not None and self.error is None and not self.cancelled


@dataclass(frozen=True, slots=True)
class AISettings:
    """Resolved AI configuration (never contains a committable secret)."""

    provider: str = "none"
    model: str = ""
    base_url: str = "https://api.openai.com/v1"
    timeout_sec: float = 20.0
    max_tokens: int = 400
    temperature: float = 0.2
    context_messages: int = 12
    api_key: str = field(default="", repr=False)   # excluded from repr/log output

    @property
    def configured(self) -> bool:
        """True only when a provider is selected and usable."""
        return self.provider not in ("", "none", "local") and bool(self.api_key)

    @property
    def provider_label(self) -> str:
        return self.provider.upper() if self.provider else "NONE"

    def masked_key(self) -> str:
        """A value safe to log or display: presence only, never the secret."""
        return "SET" if self.api_key else "UNSET"
